### ISSUE TITLE
catkin_make error !

### ISSUE THREAD

**Issue by matebearyuan** [vsu91/ewok#4]
I have no idea what's the problem, I can not find the solution on the google. Please help me !
I guess it is about Eigen library. The detail errors is in the following, thank you so much.
.... 
[78%] [ 78%] Built target polynomial_optimization_example
Building CXX object ewok/ewok_optimization/CMakeFiles/spline_optimization_example.dir/src/spline_optimization_example.cpp.o
[ 78%] Building CXX object ewok/ewok_optimization/CMakeFiles/spline_optimization_example2.dir/src/spline_optimization_example2.cpp.o
In file included from /home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/raycast_ring_buffer.h:28:0,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ed_ring_buffer.h:27,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:29,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/src/spline_optimization_example.cpp:28:
/home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ring_buffer_base.h: In instantiation of ‘void ewok::RingBufferBase<_POW, _Datatype, _Scalar>::getIdx(const Vector3&, ewok::RingBufferBase<_POW, _Datatype, _Scalar>::Vector3i&) const [with int _POW = 6; _Datatype = float; _Scalar = float; ewok::RingBufferBase<_POW, _Datatype, _Scalar>::Vector3 = Eigen::Matrix<float, 3, 1>; ewok::RingBufferBase<_POW, _Datatype, _Scalar>::Vector3i = Eigen::Matrix<int, 3, 1>]’:
/home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ed_ring_buffer.h:121:5:   required from ‘_Scalar ewok::EuclideanDistanceRingBuffer<_POW, _Datatype, _Scalar, _Flag>::getDistanceWithGrad(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&) [with Derived = Eigen::Matrix<double, 3, 1>; int _POW = 6; _Datatype = short int; _Scalar = float; _Flag = unsigned char]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:507:64:   required from ‘double ewok::UniformBSpline3DOptimization<_N, _Scalar>::collisionError(const ewok::UniformBSpline3D<_N, _Scalar>&, double, std::vector<double>&) const [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:425:67:   required from ‘double ewok::UniformBSpline3DOptimization<_N, _Scalar>::combinedError(const std::vector<double>&, std::vector<double>&) [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:358:32:   required from ‘static double ewok::UniformBSpline3DOptimization<_N, _Scalar>::wrap(const std::vector<double>&, std::vector<double>&, void*) [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:155:5:   required from ‘void ewok::UniformBSpline3DOptimization<_N, _Scalar>::setNumControlPointsOptimized(int) [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/src/spline_optimization_example.cpp:59:53:   required from here
/home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ring_buffer_base.h:70:11: error: ‘const class Eigen::ArrayWrapper<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<float>, const Eigen::Matrix<float, 3, 1> > >’ has no member named ‘floor’
       idx = (point / resolution_).array().floor().template cast<int>();
           ^
In file included from /home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/raycast_ring_buffer.h:28:0,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ed_ring_buffer.h:27,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:29,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/src/spline_optimization_example2.cpp:28:
/home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ring_buffer_base.h: In instantiation of ‘void ewok::RingBufferBase<_POW, _Datatype, _Scalar>::getIdx(const Vector3&, ewok::RingBufferBase<_POW, _Datatype, _Scalar>::Vector3i&) const [with int _POW = 6; _Datatype = float; _Scalar = float; ewok::RingBufferBase<_POW, _Datatype, _Scalar>::Vector3 = Eigen::Matrix<float, 3, 1>; ewok::RingBufferBase<_POW, _Datatype, _Scalar>::Vector3i = Eigen::Matrix<int, 3, 1>]’:
/home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ed_ring_buffer.h:121:5:   required from ‘_Scalar ewok::EuclideanDistanceRingBuffer<_POW, _Datatype, _Scalar, _Flag>::getDistanceWithGrad(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&) [with Derived = Eigen::Matrix<double, 3, 1>; int _POW = 6; _Datatype = short int; _Scalar = float; _Flag = unsigned char]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:507:64:   required from ‘double ewok::UniformBSpline3DOptimization<_N, _Scalar>::collisionError(const ewok::UniformBSpline3D<_N, _Scalar>&, double, std::vector<double>&) const [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:425:67:   required from ‘double ewok::UniformBSpline3DOptimization<_N, _Scalar>::combinedError(const std::vector<double>&, std::vector<double>&) [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:358:32:   required from ‘static double ewok::UniformBSpline3DOptimization<_N, _Scalar>::wrap(const std::vector<double>&, std::vector<double>&, void*) [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/include/ewok/uniform_bspline_3d_optimization.h:155:5:   required from ‘void ewok::UniformBSpline3DOptimization<_N, _Scalar>::setNumControlPointsOptimized(int) [with int _N = 6; _Scalar = double]’
/home/ahmad/haiwen/rotorS/src/ewok/ewok_optimization/src/spline_optimization_example2.cpp:62:53:   required from here
/home/ahmad/haiwen/rotorS/src/ewok/ewok_ring_buffer/include/ewok/ring_buffer_base.h:70:11: error: ‘const class Eigen::ArrayWrapper<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<float>, const Eigen::Matrix<float, 3, 1> > >’ has no member named ‘floor’
       idx = (point / resolution_).array().floor().template cast<int>();
           ^
make[2]: *** [ewok/ewok_optimization/CMakeFiles/spline_optimization_example.dir/src/spline_optimization_example.cpp.o] Error 1
make[1]: *** [ewok/ewok_optimization/CMakeFiles/spline_optimization_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [ewok/ewok_optimization/CMakeFiles/spline_optimization_example2.dir/src/spline_optimization_example2.cpp.o] Error 1
make[1]: *** [ewok/ewok_optimization/CMakeFiles/spline_optimization_example2.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j2 -l2" failed

**Comment by vsu91** [comment]
Hi,

Looks like you have an old version of Eigen. It should work with default Eigen in Ubuntu 16.04. If you want to use it with the version you currently have, you should change the line here: https://github.com/vsu91/ewok/blob/9d192be2c721cd4c4e664ec97872229dd47d7f17/ewok_ring_buffer/include/ewok/ring_buffer_base.h#L70

to:
```
Vector3 tmp = point / resolution_;
for(int i=0; i<3; i++)
    idx[i] = std::floor(tmp[i]);
```

**Comment by matebearyuan** [comment]
@vsu91 thanks so much, it seems the problem has been solved. But i am not sure whether the ewok project is compatible for indigo version. Because some errors happened in something including "/opt/ros/indigo/include/...". The remaining bugs like that,

 [ 93%] Building CXX object gazebo_ros_pkgs/gazebo_plugins/CMakeFiles/gazebo_ros_bumper.dir/src/gazebo_ros_bumper.cpp.o
In file included from /opt/ros/indigo/include/tf/message_filter.h:52:0,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_simulation/src/trajectory_replanning_example.cpp:40:
/opt/ros/indigo/include/message_filters/simple_filter.h: In instantiation of ‘message_filters::Connection message_filters::SimpleFilter<M>::registerCallback(void (*)(P)) [with P = const boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >&; M = sensor_msgs::Image_<std::allocator<void> >]’:
/home/ahmad/haiwen/rotorS/src/ewok/ewok_simulation/src/trajectory_replanning_example.cpp:255:51:   required from here
/opt/ros/indigo/include/message_filters/simple_filter.h:96:99: error: no matching function for call to ‘message_filters::Signal1<sensor_msgs::Image_<std::allocator<void> > >::addCallback(void (*&)(const boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >&))’
     return Connection(boost::bind(&Signal::removeCallback, &signal_, signal_.addCallback(callback)));
                                                                                                   ^
/opt/ros/indigo/include/message_filters/simple_filter.h:96:99: note: candidate is:
In file included from /opt/ros/indigo/include/message_filters/simple_filter.h:41:0,
                 from /opt/ros/indigo/include/tf/message_filter.h:52,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_simulation/src/trajectory_replanning_example.cpp:40:
/opt/ros/indigo/include/message_filters/signal1.h:91:22: note: template<class P> message_filters::Signal1<M>::CallbackHelper1Ptr message_filters::Signal1<M>::addCallback(const boost::function<void(P)>&) [with P = P; M = sensor_msgs::Image_<std::allocator<void> >]
   CallbackHelper1Ptr addCallback(const boost::function<void(P)>& callback)
                      ^
/opt/ros/indigo/include/message_filters/signal1.h:91:22: note:   template argument deduction/substitution failed:
In file included from /opt/ros/indigo/include/tf/message_filter.h:52:0,
                 from /home/ahmad/haiwen/rotorS/src/ewok/ewok_simulation/src/trajectory_replanning_example.cpp:40:
/opt/ros/indigo/include/message_filters/simple_filter.h:96:99: note:   mismatched types ‘const boost::function<void(P)>’ and ‘void (*)(const boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >&)’
     return Connection(boost::bind(&Signal::removeCallback, &signal_, signal_.addCallback(callback)));
                                                                                                   ^

**Comment by vsu91** [comment]
Software has been tested with Ubuntu 16.04 and ROS Kinetic. Unfortunately, Ubuntu 14.04 and ROS Indigo will not be supported.

**Comment by xiaopenghuang** [comment]
@vsu91 I have test on Ubuntu 14.04 and ROS Indigo.
change `ewok/ewok_simulation/src/trajectory_replanning_example.cpp`  line 255  to
```c++
tf_filter_.registerCallback(boost::bind(depthImageCallback,_1));
```
And I use eigen 3.3.2.
Everything is work fine.
